import type { Metadata } from 'next';
import ChakraUiProvider from '@/components/providers/ChakraUiProvider';
import Wrapper from '@/components/Wrapper';
import { ReactNode } from 'react';
import TanStackProvider from '@/components/providers/TanStackProvider';

export const metadata: Metadata = {
    title: 'Avatars',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body>
                <ChakraUiProvider>
                    <TanStackProvider>
                        <Wrapper>{children}</Wrapper>
                    </TanStackProvider>
                </ChakraUiProvider>
            </body>
        </html>
    );
}
